
export const skillList: string[] = [
    'Angular', 
    'Express', 
    'Node.js', 
    'REST API', 
    'PL/SQL', 
    'MySQL', 
    'SQL Server', 
    'HTML', 
    'CSS', 
    'SCSS', 
    'AJAX', 
    'Bootstrap', 
    'jQuery', 
    'JSON', 
    'JavaScript', 
    'TypeScript', 
    'Java', 
    'C#', 
    'C', 
    'C++', 
    'PHP', 
    'VB.NET', 
    'Pearl', 
    'Touchnet'
];