import {skillItem} from "../objects";
export const skillList: skillItem[] = [
    { id: 1, name: 'Angular', experience: 30, jobLink: 1 },
    { id: 2, name: 'Express', experience: 30, jobLink: 1 },
    { id: 3, name: 'Node.js', experience: 30, jobLink: 1 },
    { id: 4, name: 'REST API', experience: 60, jobLink: 1 },
    { id: 5, name: 'PL/SQL', experience: 36, jobLink: 1 },
    { id: 6, name: 'MySQL', experience: 48, jobLink: 2 },
    { id: 7, name: 'SQL Server', experience: 48, jobLink: 3 },
    { id: 8, name: 'HTML', experience: 228, jobLink: 1 },
    { id: 9, name: 'CSS', experience: 228, jobLink: 1 },
    { id: 10, name: 'SCSS', experience: 30, jobLink: 1 },
    { id: 12, name: 'AJAX', experience: 48, jobLink: 4 },
    { id: 13, name: 'Bootstrap', experience: 60, jobLink: 1 },
    { id: 14, name: 'jQuery', experience: 30, jobLink: 1 },
    { id: 15, name: 'JSON', experience: 60, jobLink: 1 },
    { id: 16, name: 'JavaScript', experience: 228, jobLink: 1 },
    { id: 17, name: 'TypeScript', experience: 30, jobLink: 1 },
    { id: 18, name: 'Java', experience: 48, jobLink: 1 },
    { id: 19, name: 'C#', experience: 48, jobLink: 3 },
    { id: 20, name: 'C', experience: 24, jobLink: 3 },
    { id: 21, name: 'C++', experience: 24, jobLink: 3 },
    { id: 22, name: 'PHP', experience: 30, jobLink: 2 },
    { id: 23, name: 'VB.NET', experience: 24, jobLink: 3 }
];